name = input("Enter your name:")
age= int(input("Enter your age:"))
city= input("Enter youur city:")
Dream_job=input("Enter your dream job:")
Fav_game= input("Enter your Favourite game name:")

print()
print("---------------PROFILE-------------")
print("Name : ",name)
print("Age : ",age)
print("City : ",city)
print("Dream Job : ",Dream_job )
print("Favourite Game : ",Fav_game)
print("-----------------------------------")
print()
print("Welcome",name, "!BEST OF LUCK FOR BECOMING A", Dream_job)